Vagrant.configure("2") do |config|

  config.vm.define :"ubuntu-focal", autostart: false do |ubuntu_focal|
    ubuntu_focal.vm.box = "ubuntu/focal64"
    ubuntu_focal.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    ubuntu_focal.vm.hostname = "ubuntu-focal"
    # ubuntu_focal.vm.network "private_network", ip: "172.24.0.11", virtualbox__intnet: "vagrant-intnet"
    ubuntu_focal.vm.synced_folder "../../", "/bootstrap"
  end

  config.vm.define :"ubuntu-bionic", autostart: false do |ubuntu_bionic|
    ubuntu_bionic.vm.box = "ubuntu/bionic64"
    ubuntu_bionic.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
      vb.customize ["modifyvm", :id, "--uart1", "off"]
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
    ubuntu_bionic.vm.hostname = "ubuntu-bionic"
    # ubuntu_bionic.vm.network "private_network", ip: "172.24.0.12", virtualbox__intnet: "vagrant-intnet"
    ubuntu_bionic.vm.synced_folder "../../", "/bootstrap"
  end
end
